name: Lab 4 (Lint and Unit Test)

on: 
  push: 
    branches: 
      main 
  pull_request: 
    branches: 
      main 
      
jobs: 
  lint: 
    if: false
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v7 

      - name: Use Node.js 24.x 
        uses: actions/setup-node@v7 
        with: 
          node-version: "24" 

      - name: Install Deps
        run: npm install

      - name: Run Lint
        run: npm run lint

  unit-test: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v7 

      - name: Use Node.js 24.x 
        uses: actions/setup-node@v7 
        with: 
          node-version: "24" 

      - name: Install Deps
        run: npm install

      - name: Run Unit Tests
        run: npm run test:ci
      - if: success() || failure() 
        uses: actions/upload-artifact@v7 
        with: 
          name: unit-test-${{ github.sha }} 
          path: coverage/lcov-report
